apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default # 属于的名称空间
  name: pod-reader-r
rules: # 当前角色的规则
- apiGroups: [""] # "" 标明 core API 组
  resources: ["pods","deployments"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader-cr
rules:
- apiGroups: [""]
  resources: ["secrets"] # 在HTTP层面用来访问 Secret 资源的名称为 "secrets"。
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["configmaps"] # 在HTTP层面用来访问 Secret 资源的名称为 "secrets"。
  verbs: ["get", "watch", "list"]