apiVersion: v1
kind: Service
metadata:
  name: cluster-svc-test
  namespace: default
spec:
  selector:
    app: cluster-svc-test
  clusterIP: 10.1.246.118 # 通过clusterIP 手动指定IP，默认会自动分配
  type: ClusterIP
  ports:
  - name: tomcat
    protocol: TCP
    port: 80
    targetPort: 8080
  - name:  redis
    port: 90
    targetPort: 6379