apiVersion: v1
kind: Pod
metadata:
  name: "pod-nfs-01"
  namespace: default
  labels:
    app: "pod-nfs-01"
spec:
  containers:
  - name: pod-nfs-01
    image: "nginx"
    ports:
    - containerPort:  80
      name:  http
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
    - name: html
      mountPath: /usr/share/nginx/html/
      type: DirectorOrCreate # type是个文件夹
  volumes:
    - name: localtime
      hostPath:
        path: /usr/share/zoneinfo/Asia/Shanghai
    - name: html
      nfs:
        server: 192.168.122.11 # IP 是NFS服务器的地址
        path: /nfs/data/nginx/
