apiVersion: v1
kind: Pod
metadata:
  name: "pod-secret-volume"
  namespace: default
  labels:
    app: "pod-secret-volume"
spec:
  containers:
  - name: pod-secret-volume
    image: "debian-slim:latest"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - name: app # 挂载名称
      mountPath: /app # 挂载路径(/app路径挂载出去)
  volumes:
  - name: app
    secret:
      defaultMode: 0777
      secretName: dev-db-secret # secret name
      items:
        - key: password.txt # dev-db-secret 里面的password.txt的key内容挂出来
          path: pwd.md # 默认secret里面数据的key是作为文件名，path是自己重新名称