apiVersion: v1
kind: Pod
metadata:
  name: "pod-secret-test"
  namespace: default
  labels:
    app: "pod-secret-test"
spec:
  containers:
  - name: pod-secret-test
    image: "busybox"
    command: ["/bin/sh","-c","sleep 3600"]
    env:
    - name: DB_HOST
      valueFrom:
        secretKeyRef: # secret 的内容
          name: dev-db-secret # secret 名字
          key: username # 自定base64解码
    - name: POD_NAME
      fieldRef: # 属性引用
      fieldPath: metadata.name # 取出资源对象信息