apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-volumes-10m
  namespace: default
  labels:
    app: local
spec:
  storageClassName: my-nfs-storeage # 存储名称
  capacity:
    storage: 10m
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.122.11 # IP 是NFS服务器的地址
    path: /nfs/data/haha/